config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"

  controller :dashboards do
    get :index, as: :dashboard, path: :dashboard
  end
  resources :farms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/farm.rb
# == Schema Information
#
# Table name: farms
#
#  id         :bigint           not null, primary key
#  city       :string           not null
#  country    :string           default("France"), not null
#  latitude   :float
#  longitude  :float
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_farms_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Farm < ApplicationRecord
  belongs_to :user
  validates :name, :city, :country, presence: true, allow_blank: false

  geocoded_by :city
  after_validation :geocode

  def address
    [city, country].compact.join(', ')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, :email, uniqueness: true, presence: true, allow_blank: false

  has_one :farm, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  before_action :authenticate_user!
  after_action :verify_authorized, unless: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index
    authorize :dashboard, :index?
  end
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  def new
    redirect_to root_path if current_user.farm.present?
    @farm = Farm.new
    authorize @farm
  end

  def create
    authorize :farm, :create?
    @farm = Farm.new(farm_params)
    @farm.user = current_user
    if @farm.save
      redirect_to @farm, notice: t('.farm_created')
    else
      render :new, alert: t('errors.form_not_valid')
    end
  end

  def show
    @farm = Farm.find(params[:id])
    authorize @farm

    @markers = [{
        lat: @farm.latitude,
        lng: @farm.longitude,
        name: @farm.name,
        info_window_html: render_to_string(partial: "info_window", locals: {object: @farm})
        }]
  end

  private

  def farm_params
    params.require(:farm).permit(:name, :city, :country)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    authorize :page, :index?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breadcrumbs_helper.rb
module BreadcrumbsHelper
  def build_breadcrumbs(page_title, parents = [])
    html = ''
    html << content_tag(:h1, page_title, class: 'page-heading d-flex text-dark fw-bold fs-3 flex-column justify-content-center my-0')
    html << content_tag(:ul, home_link + parents_links(parents) + separator + current_page(page_title),
                        class: 'breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1')
    html.html_safe
  end

  private

  def separator
    content_tag :li, class: 'breadcrumb-item' do
      tag.span class: 'bullet bg-gray-400 w-5px h-2px'
    end
  end

  def home_link
    content_tag :li, class: 'breadcrumb-item text-muted' do
      link_to t('home'), root_path, class: 'text-muted text-hover-primary'
    end
  end

  def parents_links(parents)
    return unless parents.any?

    parents.each do |parent|
      separator
      content_tag 'li', class: 'breadcrumb-item' do
        link_to parent[:title], parent[:path], class: 'text-muted text-hover-primary'
      end
    end
  end

  def current_page(page_title)
    content_tag :li, page_title, class: 'breadcrumb-item text-muted'
  end
end

app/views/dashboards/index.html.haml
- content_for :title do
  = t('pages.dashboard')
- content_for :layout do
  .row.g-5.g-xl-10.mb-5.mb-xl-10
    - if current_user.farm.blank?
      .col-xxl-6
        -# = render 'partials/widgets/engage/no_farm'
  -#   .col-md-6.col-lg-6.col-xl-6.col-xxl-3.mb-md-5.mb-xl-10
  -#     = render 'partials/widgets/cards/widget-20'
  -#     = render 'partials/widgets/cards/widget-7'
  -#   .col-md-6.col-lg-6.col-xl-6.col-xxl-3.mb-md-5.mb-xl-10
  -#     = render 'partials/widgets/cards/widget-17'
  -#     = render 'partials/widgets/lists/widget-26'
  -# .row.gx-5.gx-xl-10
  -#   .col-xxl-6.mb-5.mb-xl-10
  -#     = render 'partials/widgets/charts/widget-8'
  -#   .col-xl-6.mb-5.mb-xl-10
  -#     = render 'partials/widgets/tables/widget-16'
  -# .row.g-5.g-xl-10.mb-5.mb-xl-10
  -#   .col-xxl-6
  -#     = render 'partials/widgets/cards/widget-18'
  -#   .col-xl-6
  -#     = render 'partials/widgets/charts/widget-36'
  -# .row.g-5.g-xl-10.mb-5.mb-xl-10
  -#   .col-xl-4
  -#     = render 'partials/widgets/charts/widget-35'
  -#   .col-xl-8
  -#     = render 'partials/widgets/tables/widget-14'
  -# .row.gx-5.gx-xl-10
  -#   .col-xl-4
  -#     = render 'partials/widgets/charts/widget-31'
  -#   .col-xl-8
  -#     = render 'partials/widgets/charts/widget-24'

app/views/farms/_info_window.html.haml
= object.name

app/views/farms/_map.html.haml
.card.card-flush.h-xl-100
  .card-header
    %h3.card-title= t('.properties')
  .card-body
    %div.h-100{"data-controller" => "map", "data-map-api-key-value" => "#{ENV['MAPBOX_API_KEY']}", "data-map-markers-value" => "#{@markers.to_json}"}

app/views/farms/_no_farm.html.haml
/ begin::Engage widget 10
.card.card-flush.h-md-100
  / begin::Body
  .card-body.d-flex.flex-column.justify-content-between.mt-9.bgi-no-repeat.bgi-size-cover.bgi-position-x-center.pb-0
    / begin::Wrapper
    .mb-10
      / begin::Title
      .fs-2hx.fw-bold.text-gray-800.text-center.mb-13
        %span.me-2= t('.you_have_no_farm')
      / end::Title
      / begin::Action
      .text-center
        = link_to t('.build_a_farm'), new_farm_path, class: 'btn btn-primary fw-bold'
      / begin::Action
    / begin::Wrapper
    / begin::Illustration
    = image_tag 'farms/farm-buildings.webp', class: 'mx-auto h-200px h-lg-300px'
    -# %img.mx-auto.h-150px.h-lg-200px.theme-light-show{:alt => "", :src => "#{asset_path('illustrations/misc/upgrade.svg')}"}/
    -# %img.mx-auto.h-150px.h-lg-200px.theme-dark-show{:alt => "", :src => "#{asset_path('illustrations/misc/upgrade-dark.svg')}"}/
    / end::Illustration
  / end::Body
/ end::Engage widget 10

app/views/farms/new.html.haml
- content_for :title do
  = t('pages.new_farm')

- content_for :breadcrumbs do
  = build_breadcrumbs(t('pages.new_farm'))

- content_for :layout do
  .row.g-5.g-xl-10.mb-5.mb-xl-10
    .alert.alert-primary.d-flex.align-items-center.p-5.mb-10
      %i.ki-duotone.ki-shield-tick.fs-2hx.text-primary.me-4
        %span.path1
        %span.path2
      .d-flex.flex-column
        %h4.mb-1.text-primary= t('.info')
        %span= t('.only_france')
    .col-md-8.offset-md-2.col-12
      .card.shadow-sm
        .card-header
          %h3.card-title= t('.create_my_farm')
        .card-body
          = simple_form_for @farm, html: { 'data-turbo': "false" } do |f|
            = f.input :name
            = f.input :city, input_html: {class: "d-none", data: {address_autocomplete_target: "address"}},
            wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["CITY_AUTOCOMPLETE"]}}
            %fieldset{ disabled: 'disabled'}
              = f.input :country, only: ["FR"], selected: "FR"
            = f.button :submit, t('.submit')

app/views/farms/show.html.haml
- content_for :title do
  = t('pages.farm')

- content_for :breadcrumbs do
  = build_breadcrumbs(t('pages.farm'))

- content_for :layout do
  .row.g-5.g-xl-10.mb-5.mb-xl-10
    - if current_user.farm.blank?
      .col-xxl-6
        = render 'no_farm'

    .col-xl-6.mb-5.mb-xl-1
      = render 'map'

app/views/layouts/_flash.haml
- if flash.any?
  .bg-body-secondary.position-relative.bd-example-toasts.rounded-3{ aria: { atomic: "true", live: "polite" } }
    .toast-container.p-3.top-0.end-0
      - flash.each do |flash_type, message|
        .toast.show.align-items-center.border-0{ class: "#{flash_type}", "aria-atomic" => "true", "aria-live" => "assertive", role: "alert"}
          .d-flex
            .toast-body
              = message
            %button.btn-close.btn-close-white.me-2.m-auto{ "aria-label":  "Close", "data-bs-dismss": "toast", type: "button" }

app/views/layouts/_navbar.html.haml
%nav
  - if user_signed_in?
    .px-3.py-2.text-bg-dark.border-bottom
      .container
        .d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
          %a.d-flex.align-items-center.my-2.my-lg-0.me-lg-auto.text-white.text-decoration-none{href: "/"}
            %svg.bi.me-2{"aria-label" => "Bootstrap", height: "32", role: "img", width: "40"}
              %use{"xlink:href" => "#bootstrap"}
          %ul.nav.col-12.col-lg-auto.my-2.justify-content-center.my-md-0.text-small
            %li
              %a.nav-link.text-secondary{href: "#"}
                %svg.bi.d-block.mx-auto.mb-1{height: "24", width: "24"}
                  %use{"xlink:href" => "#home"}
                Home
            %li
              %a.nav-link.text-white{href: "#"}
                %svg.bi.d-block.mx-auto.mb-1{height: "24", width: "24"}
                  %use{"xlink:href" => "#speedometer2"}
                Dashboard
            %li
              %a.nav-link.text-white{href: "#"}
                %svg.bi.d-block.mx-auto.mb-1{height: "24", width: "24"}
                  %use{"xlink:href" => "#table"}
                Orders
            %li
              %a.nav-link.text-white{href: "#"}
                %svg.bi.d-block.mx-auto.mb-1{height: "24", width: "24"}
                  %use{"xlink:href" => "#grid"}
                Products
            %li
              %a.nav-link.text-white{href: "#"}
                %svg.bi.d-block.mx-auto.mb-1{height: "24", width: "24"}
                  %use{"xlink:href" => "#people-circle"}
                Customers
  .px-3.py-2.border-bottom.mb-3.bg-primary
    .d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
      %a.d-flex.align-items-center.mb-2.text-black.mb-lg-0.text-decoration-none{href: "/"}
        -# %svg.bi.me-2{"aria-label" => "Bootstrap", height: "32", role: "img", width: "40"}
        -#   %use{"xlink:href" => "#bootstrap"}
        .bi.me-2= t('site_name')
      %ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
        %li
          %a.nav-link.px-2.text-black{href: "#"}= t('home')
        %li
          %a.nav-link.px-2.text-black{href: "#"} Features
        %li
          %a.nav-link.px-2.text-black{href: "#"} Pricing
        %li
          %a.nav-link.px-2.text-black{href: "#"} FAQs
        %li
          %a.nav-link.px-2.text-black{href: "#"} About
      .text-end
        - if user_signed_in?
          .nav-item.dropdown
          %button.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", role: "button"}
            %span.bi.bi-person-fill{ 'aria-hidden': 'true' }
          %ul.dropdown-menu.dropdown-menu-lg-end
            %li
              = link_to t('.profile'), edit_user_registration_path, class: 'dropdown-item'
            %li
              = link_to t('devise.sessions.sign_out'), destroy_user_session_path, method: :delete, class: 'dropdown-item'
        - else
          = link_to t('devise.sessions.sign_in'), new_user_session_path, class: 'btn btn-secondary'
          = link_to t('devise.registrations.signe_up'), new_user_registration_path, class: 'btn btn-warning'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FarmerSimulation
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    = render 'layouts/navbar'
    = render partial:'layouts/flash'
    = yield

app/views/pages/index.html.haml
.container
  .row
    .col
      %h1= t('site_name')
  .row
    .col
      = image_tag 'home-header', class: 'img-fluid'